### ISSUE TITLE
macOS 15 - all jobs stuck at "Waiting for the VM to boot and be SSH-able..."

### ISSUE THREAD

**Issue by hschroeder-worldiety** [cirruslabs/gitlab-tart-executor#86]
Hey there we updated our mac mini M1 runner from 14.7 to 15.0 yesterday.

The gitlab-tart-executor stopped working after the update to macOS 15.

```
Running with gitlab-runner 17.4.0 (b92ee590)
  on ...
Preparing the "custom" executor
03:00:05
Using Custom executor...
2024/09/23 16:56:51 Pulling the latest version of ghcr.io/cirruslabs/macos-runner:sonoma...
2024/09/23 16:56:52 Cloning and configuring a new VM...
2024/09/23 16:56:52 Waiting for the VM to boot and be SSH-able...
ERROR: Preparation failed: unknown Custom executor executable exit code -1; executable execution terminated with: signal: terminated
```

When looking at `tart list` and the graphs of the activity viewer I can see that the vm should be booted and is in a idle state afterwards.

We have a customized the gitlab-runner config, but the problem is also present with the default config.

```
concurrent = 2

[[runners]]
  # ...
  executor = "custom"
  [runners.feature_flags]
    FF_RESOLVE_FULL_TLS_CHAIN = false
  [runners.custom]
    config_exec = "gitlab-tart-executor"
    config_args = ["config"]
    prepare_exec = "gitlab-tart-executor"
    prepare_args = ["prepare"]
    run_exec = "gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "gitlab-tart-executor"
    cleanup_args = ["cleanup"]
```

Hope someone can help me with this.

**Comment by edigaryev** [comment]
This is likely related to the newly introduced "Local Network" permission in macOS Sequoia and the fact that GitLab Runner's binary has no `LC_UUID` identifier, which is critical for the Apple's Transparency Consent and Control framework.

Can you check if the work around in https://github.com/cirruslabs/gitlab-tart-executor/issues/85#issuecomment-2363353178 works for you?

Without re-building the GitLab Runner the permission cannot take effect, even if you've explicitly allowed it in the GUI.

**Comment by hschroeder-worldiety** [comment]
Thanks alot! This worked.

Hopefully the `LC_UUID` Identifier is included when gitlab-runner 17.5 is released.

Never thought it would be a `gitlab-runner` issue, as our other mac runs just fine using the shell executor and macOS 15.

**Comment by hschroeder-worldiety** [comment]
Update: Upstream is still not fixed in gitlab-runner 17.5

**Comment by edigaryev** [comment]
Thanks to @waddles, [this is now fixed](https://github.com/Homebrew/homebrew-core/commit/77fcd447733f6f063ef4f635202d3748fdfb8e26) in the latest [Homebrew version of GitLab Runner](https://formulae.brew.sh/formula/gitlab-runne) (`>=17.6.0`).

I've created https://github.com/cirruslabs/gitlab-tart-executor/pull/94 to reflect this in the README.md.

**Comment by FlixFranz** [comment]
I still have the issue, the VM starts but hangs with `2025/07/07 10:26:03 Waiting for the VM to boot and be SSH-able...` nothing happens, until the timeout kicks in. On the runners mac I see the tart-window open with the booted vm.

I am using the latest version of gitlab-runner from homebrew (see logs): 


```
macrunner@Mac-mini-von-Mac-Runner-02 ~ % which gitlab-runner 
/opt/homebrew/bin/gitlab-runner
macrunner@Mac-mini-von-Mac-Runner-02 ~ % gitlab-runner --version
Version:      18.1.1
Git revision: 2b813ade
Git branch:   18-1-stable
GO version:   go1.24.4
Built:        2025-06-26T16:25:31+00:00
OS/Arch:      darwin/arm64
macrunner@Mac-mini-von-Mac-Runner-02 ~ % dwarfdump --uuid /opt/homebrew/bin/gitlab-runner 
UUID: D1F40BAA-CDB2-3332-D881-AACF61B5B47F (arm64) /opt/homebrew/bin/gitlab-runner
```

I have no problems connecting to a vm using ssh in terminal: 

```
macrunner@Mac-mini-von-Mac-Runner-02 ~ % tart list
Source Name                                                                                                           Disk Size SizeOnDisk State  
local  gitlab-1220746                                                                                                 120  80   80         stopped
local  gitlab-1220759                                                                                                 120  80   80         stopped
local  gitlab-1220774                                                                                                 120  80   80         running
local  macos-sequoia-xcode                                                                                            120  80   80         stopped
OCI    ghcr.io/cirruslabs/macos-sequoia-xcode:latest                                                                  120  81   81         stopped
OCI    ghcr.io/cirruslabs/macos-sequoia-xcode@sha256:337c389b3b132cc868d42f40c715b943f263175c5fff50a78856e899be1175df 120  81   81         stopped
macrunner@Mac-mini-von-Mac-Runner-02 ~ % ssh admin@`tart ip gitlab-1220774`
The authenticity of host '192.168.64.18 (192.168.64.18)' can't be established.
ED25519 key fingerprint is SHA256:8tL8jjcEU6X7PWkWudEqDp3RUd8CH/Id+VOII9hdKp0.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:1: 192.168.64.14
    ~/.ssh/known_hosts:4: 192.168.64.15
    ~/.ssh/known_hosts:5: 192.168.64.17
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.64.18' (ED25519) to the list of known hosts.
(admin@192.168.64.18) Password:
Last login: Mon Jul  7 08:26:15 2025
admin@Manageds-Virtual-Machine ~ % 
```

not really sure where to look. The host mac is running Sequoia 15.5. I am connected via Screen Sharing, logged in as a non-admin-user `macrunner`.

**Comment by edigaryev** [comment]
@ogezue, @FlixFranz on the GitLab Runner machine, can you check if all instances of `gitlab-runner` app are allowed  in `System Settings → Privacy & Security → Local Network`?

**Comment by edigaryev** [comment]
@FlixFranz at this point the best workaround is to probably invoke `gitlab-runner` from Terminal (in a GUI session).

That should completely bypass the "Local Network" permission check AFAIR.

**Comment by FlixFranz** [comment]
According to https://developer.apple.com/documentation/technotes/tn3179-understanding-local-network-privacy#Reset-local-network-state I try it with a new account, if this fails i run it from the Terminal. Thanks for your time!

**Comment by kartikprakash1** [comment]
Hi we are running into this same issue after enabling the setting under Local Network as well.

Here are the details:

```
~ % gitlab-tart-executor -v
executor version 1.26.0-404bafe
```

```
~ % tart --version
2.28.5
```

```
~ % gitlab-runner -v
Version:      18.3.1
Git revision: 5a021a1c
Git branch:   18-3-stable
GO version:   go1.25.1
Built:        2025-09-04T15:24:16+00:00
OS/Arch:      darwin/arm64
```

```
MacOS Sequoia Version 15.3.1 (24D70)
```
